options:
  #max-time: 5 # minutes
  docker: true

pipelines:
  custom:
    deploy-to-test:
      - step:
          image: gcr.io/google.com/cloudsdktool/cloud-sdk:338.0.0-alpine
          name: Deploy to GCP
          deployment: test
          caches:
            - docker
          script:
            - ./.build/build.sh $BITBUCKET_DEPLOYMENT_ENVIRONMENT

  branches:
    master:
      - step:
          image: gcr.io/google.com/cloudsdktool/cloud-sdk:338.0.0-alpine
          name: Deploy to GCP
          deployment: production
          caches:
            - docker
          script:
            - ./.build/build.sh $BITBUCKET_DEPLOYMENT_ENVIRONMENT
