image: python:3.7-slim

pipelines:
  custom:
    create-cert:
      - step:
          caches:
            - pip
          name: Main script
          script:
            # Installing dependencies
            - apt update
            - apt install -y certbot git
            - pip install -r requirements.txt
            # Managing files
            - rm -r /etc/letsencrypt/
            - ln -s $(pwd)/letsencrypt/ /etc/
            - echo dns_cloudflare_api_token = $CLOUDFLARE_TOKEN > letsencrypt/cloudflare.ini
            # Running main code
            - python main.py
