image: python:3.7.10-alpine3.13

pipelines:
  custom:
    create-cert:
      - step:
          caches:
            - pip
          name: Main script
          script:
            # Installing dependencies
            - apk update
            - apk add git
            - pip install --upgrade pip3
            - pip3 install -r requirements.txt
            # Installing Docker
            - curl -fsSL https://get.docker.com | sh
            # Running main code
            - python main.py $GMAIL_PASSWORD
