image: gcr.io/google.com/cloudsdktool/cloud-sdk:334.0.0

pipelines:
  custom:
    list-certs:
      - step:
          image: python:3.7-slim
          caches:
            - pip
          name: Main script
          script:
            # Installing dependencies
            - apt update
            - apt install -y certbot=0.31.0-1+deb10u1 git
            - pip install .
            # Managing files
            - rm -r /etc/letsencrypt/
            - ln -s $(pwd)/letsencrypt/ /etc/
            - echo dns_cloudflare_api_token = $CLOUDFLARE_TOKEN > letsencrypt/cloudflare.ini
            # Running main code
            - export ROOT_DIR=$(pwd)
            - python3 run.py --list-certs
